In [1]:
!pip install -q --upgrade jax jaxlib

     |████████████████████████████████| 225kB 2.7MB/s 
     |████████████████████████████████| 24.9MB 1.5MB/s 


In [0]:
from __future__ import print_function, division
import jax.numpy as np
from jax import grad, jit, vmap,jacfwd, jacrev
from jax import random

In [0]:
def merge(left,right):
  result=[]
  
  left_idx,right_idx=0,0
  
  while left_idx<len(left) and right_idx< len(right):
    if left[left_idx]<=right[right_idx]:
      result.append(left[left_idx])
      left_idx+=1
    else:
      result.append(right[right_idx])
      right_idx+=1
      
  if len(left)>left_idx:
    result.extend(left[left_idx:])
  if len(right)>right_idx:
    result.extend(right[right_idx:])
  return result

In [0]:
def mergesort(arr):
  if len(arr)<=1:
    return arr
  middle=len(arr)//2
  
  left=arr[0:middle]
  right=arr[middle:]  
 
  left=mergesort(left)
  right=mergesort(right)
  
  res=merge(left,right)
  return res

In [16]:
key = random.PRNGKey(42)
test_array=random.normal(key,(5,))
test_array

DeviceArray([ 0.61226517,  1.12258828, -0.85441345, -0.8127327 ,
             -0.89040512], dtype=float32)

In [17]:
jacfwd(mergesort)(test_array)

[DeviceArray([0., 0., 0., 0., 1.], dtype=float32),
 DeviceArray([0., 0., 1., 0., 0.], dtype=float32),
 DeviceArray([0., 0., 0., 1., 0.], dtype=float32),
 DeviceArray([1., 0., 0., 0., 0.], dtype=float32),
 DeviceArray([0., 1., 0., 0., 0.], dtype=float32)]

In [18]:
jacrev(mergesort)(test_array)

[DeviceArray([0., 0., 0., 0., 1.], dtype=float32),
 DeviceArray([0., 0., 1., 0., 0.], dtype=float32),
 DeviceArray([0., 0., 0., 1., 0.], dtype=float32),
 DeviceArray([1., 0., 0., 0., 0.], dtype=float32),
 DeviceArray([0., 1., 0., 0., 0.], dtype=float32)]